telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 33, in planet
    text_list = update.message.text.split()
AttributeError: 'NoneType' object has no attribute 'text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 80, in remind_city_game
    if username in city_game_config.keys():
NameError: name 'city_game_config' is not defined
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 88, in m
    if username not in city_game_config.keys():
NameError: name 'city_game_config' is not defined
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 74, in init_city_game
    city_game_config[username] = {'cities_whitelist':city_list, 'last_letter': 'any', 'cities_blacklist':[]}
NameError: name 'city_game_config' is not defined
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 74, in init_city_game
    city_game_config[username] = {'cities_whitelist':city_list, 'last_letter': 'any', 'cities_blacklist':[]}
NameError: name 'city_game_config' is not defined
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 81, in remind_city_game
    if username in city_game_config.keys():
NameError: name 'city_game_config' is not defined
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 100, in m
    if user_city in whitelist and (user_city[0] == last_letter or last_letter == 'any'):
IndexError: string index out of range
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 89, in m
    username = update.message.chat.username
AttributeError: 'NoneType' object has no attribute 'chat'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 63, in next_full_moon
    text_list = update.message.text.split()
AttributeError: 'NoneType' object has no attribute 'text'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 63, in next_full_moon
    text_list = update.message.text.split()
AttributeError: 'NoneType' object has no attribute 'text'
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 63, in next_full_moon
    text_list = update.message.text.split()
AttributeError: 'NoneType' object has no attribute 'text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 53, in wordcount
    text = update.message.text.replace('/wordcount','').replace('-','').strip()
AttributeError: 'NoneType' object has no attribute 'text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 136, in calc
    parsed_sting = re.findall('\d+|[+,-,*,/]', text)
NameError: name 're' is not defined
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 136, in calc
    parsed_sting = re.findall('\d+|[+,-,*,/]', text)
NameError: name 're' is not defined
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 136, in calc
    parsed_sting = re.findall('\d+|[+,-,*,/]', text)
NameError: name 're' is not defined
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 153, in calc
    update.message.reply_text(f'Transformed your query in {" ".joint(filtered_list)}')
AttributeError: 'str' object has no attribute 'joint'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 154, in calc
    update.message.reply_text(f'Transformed your query in {" ".joint(filtered_list)}')
AttributeError: 'str' object has no attribute 'joint'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 154, in calc
    update.message.reply_text(f'Transformed your query in {" ".joint(filtered_list)}')
AttributeError: 'str' object has no attribute 'joint'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "bot.py", line 167, in calc
    filtered_list[i] = float(filtered_list[i-1]) / float(filtered_list[i+1])
ZeroDivisionError: float division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 186, in calc
    update.message.reply_text(e)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/message.py", line 478, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/bot.py", line 258, in send_message
    timeout=timeout, **kwargs)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/utils/request.py", line 325, in post
    body=json.dumps(data).encode('utf-8'),
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ZeroDivisionError is not JSON serializable
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 132, in calc
    text = update.message.text.replace('/calc','').strip()
AttributeError: 'NoneType' object has no attribute 'text'
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
